domain: www.solisec.org
url: https://www.solisec.org/
baseurl: /rejoice4156.github.io/

theme: jekyll-theme-minimal
title: Karl's Website
description: My Personal GitHub Pages Site (in development)
logo: profile_picture.jpg
